### ISSUE TITLE
Doesn't work exactly like in the README

### ISSUE THREAD

**Issue by RogueMacro** [M0n7y5/BeefIDE-SimplyDark#2]
I couldn't get the IDE to fully adapt the theme without deleting any UI.png, UI_2.png, or UI_4.png files it had generated, then manually copying psd/UI_4.psd to the bin/themes/SimplyDark directory, then loading the theme.

**Comment by M0n7y5** [comment]
I am gonna look into that

**Comment by M0n7y5** [comment]
Should be fixed
